# Generated by Django 2.2.4 on 2020-06-08 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_teashop', '0002_auto_20200608_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teashop',
            old_name='images',
            new_name='picture',
        ),
    ]
